### ISSUE TITLE
Wrong requirements

### ISSUE THREAD

**Issue by ostrolucky** [PatchRanger/cartesian-iterator#2]
Says it supports PHP 5.0, uses scalar typehints

**Comment by PatchRanger** [comment]
Nice catch, thank you! As statistics says https://blog.packagist.com/php-versions-stats-2018-2-edition/ , there is a little need in supporting PHP 5 version - so I prefer to raise the requirement: https://github.com/PatchRanger/cartesian-iterator/commit/925d2d3ee4e8df892292847d73ff5ec285653a25 .
