### ISSUE TITLE
Incompatible return type for PatchRanger\CartesianIterator::key()

### ISSUE THREAD

**Issue by nicodemuz** [PatchRanger/cartesian-iterator#5]
When running on PHP 8.1, I get the following deprecation notice:
> PHP Deprecated:  Return type of PatchRanger\CartesianIterator::key(): int should either be compatible with MultipleIterator::key(): array, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nico/Projects/online-store/symfony/vendor/patchranger/cartesian-iterator/src/CartesianIterator.php on line 36

**Comment by PatchRanger** [comment]
@nicodemuz Thanks for reporting. This should be fixed for now (if not - please let me know).

**Comment by PatchRanger** [comment]
@nicodemuz Please notice the required by this fix change in behavior:
```
$result = iterator_to_array($cartesianIterator, false);
```
\- we can't preserve keys anymore, we must force to overwrite them.
